/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VerifiedOwnersRouteImport } from './routes/verified-owners'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SearchMapRouteImport } from './routes/search-map'
import { Route as RoomsInDehradunRouteImport } from './routes/rooms-in-dehradun'
import { Route as PropertiesInUttarakhandRouteImport } from './routes/properties-in-uttarakhand'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PremiumHomesRouteImport } from './routes/premium-homes'
import { Route as PgInPremNagarRouteImport } from './routes/pg-in-prem-nagar'
import { Route as PgInDehradunRouteImport } from './routes/pg-in-dehradun'
import { Route as PgHostelsRouteImport } from './routes/pg-hostels'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FlatsInDehradunRouteImport } from './routes/flats-in-dehradun'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMyListingsRouteImport } from './routes/dashboard.my-listings'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAddPropertyRouteImport } from './routes/dashboard.add-property'
import { Route as CollegesCollegeSlugRouteImport } from './routes/colleges.$collegeSlug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as DashboardEditPropertyIdRouteImport } from './routes/dashboard.edit-property.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedOwnersRoute = VerifiedOwnersRouteImport.update({
  id: '/verified-owners',
  path: '/verified-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchMapRoute = SearchMapRouteImport.update({
  id: '/search-map',
  path: '/search-map',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsInDehradunRoute = RoomsInDehradunRouteImport.update({
  id: '/rooms-in-dehradun',
  path: '/rooms-in-dehradun',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesInUttarakhandRoute = PropertiesInUttarakhandRouteImport.update({
  id: '/properties-in-uttarakhand',
  path: '/properties-in-uttarakhand',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumHomesRoute = PremiumHomesRouteImport.update({
  id: '/premium-homes',
  path: '/premium-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const PgInPremNagarRoute = PgInPremNagarRouteImport.update({
  id: '/pg-in-prem-nagar',
  path: '/pg-in-prem-nagar',
  getParentRoute: () => rootRouteImport,
} as any)
const PgInDehradunRoute = PgInDehradunRouteImport.update({
  id: '/pg-in-dehradun',
  path: '/pg-in-dehradun',
  getParentRoute: () => rootRouteImport,
} as any)
const PgHostelsRoute = PgHostelsRouteImport.update({
  id: '/pg-hostels',
  path: '/pg-hostels',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatsInDehradunRoute = FlatsInDehradunRouteImport.update({
  id: '/flats-in-dehradun',
  path: '/flats-in-dehradun',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyListingsRoute = DashboardMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddPropertyRoute = DashboardAddPropertyRouteImport.update({
  id: '/add-property',
  path: '/add-property',
  getParentRoute: () => DashboardRoute,
} as any)
const CollegesCollegeSlugRoute = CollegesCollegeSlugRouteImport.update({
  id: '/colleges/$collegeSlug',
  path: '/colleges/$collegeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditPropertyIdRoute = DashboardEditPropertyIdRouteImport.update({
  id: '/edit-property/$id',
  path: '/edit-property/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/flats-in-dehradun': typeof FlatsInDehradunRoute
  '/journal': typeof JournalRoute
  '/pg-hostels': typeof PgHostelsRoute
  '/pg-in-dehradun': typeof PgInDehradunRoute
  '/pg-in-prem-nagar': typeof PgInPremNagarRoute
  '/premium-homes': typeof PremiumHomesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/properties-in-uttarakhand': typeof PropertiesInUttarakhandRoute
  '/rooms-in-dehradun': typeof RoomsInDehradunRoute
  '/search-map': typeof SearchMapRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/verified-owners': typeof VerifiedOwnersRoute
  '/wishlist': typeof WishlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/colleges/$collegeSlug': typeof CollegesCollegeSlugRoute
  '/dashboard/add-property': typeof DashboardAddPropertyRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-listings': typeof DashboardMyListingsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit-property/$id': typeof DashboardEditPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/explore': typeof ExploreRoute
  '/flats-in-dehradun': typeof FlatsInDehradunRoute
  '/journal': typeof JournalRoute
  '/pg-hostels': typeof PgHostelsRoute
  '/pg-in-dehradun': typeof PgInDehradunRoute
  '/pg-in-prem-nagar': typeof PgInPremNagarRoute
  '/premium-homes': typeof PremiumHomesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/properties-in-uttarakhand': typeof PropertiesInUttarakhandRoute
  '/rooms-in-dehradun': typeof RoomsInDehradunRoute
  '/search-map': typeof SearchMapRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/verified-owners': typeof VerifiedOwnersRoute
  '/wishlist': typeof WishlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/colleges/$collegeSlug': typeof CollegesCollegeSlugRoute
  '/dashboard/add-property': typeof DashboardAddPropertyRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-listings': typeof DashboardMyListingsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/edit-property/$id': typeof DashboardEditPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/flats-in-dehradun': typeof FlatsInDehradunRoute
  '/journal': typeof JournalRoute
  '/pg-hostels': typeof PgHostelsRoute
  '/pg-in-dehradun': typeof PgInDehradunRoute
  '/pg-in-prem-nagar': typeof PgInPremNagarRoute
  '/premium-homes': typeof PremiumHomesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/properties-in-uttarakhand': typeof PropertiesInUttarakhandRoute
  '/rooms-in-dehradun': typeof RoomsInDehradunRoute
  '/search-map': typeof SearchMapRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/verified-owners': typeof VerifiedOwnersRoute
  '/wishlist': typeof WishlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/colleges/$collegeSlug': typeof CollegesCollegeSlugRoute
  '/dashboard/add-property': typeof DashboardAddPropertyRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-listings': typeof DashboardMyListingsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit-property/$id': typeof DashboardEditPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/flats-in-dehradun'
    | '/journal'
    | '/pg-hostels'
    | '/pg-in-dehradun'
    | '/pg-in-prem-nagar'
    | '/premium-homes'
    | '/press'
    | '/privacy'
    | '/properties-in-uttarakhand'
    | '/rooms-in-dehradun'
    | '/search-map'
    | '/security'
    | '/terms'
    | '/verified-owners'
    | '/wishlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/colleges/$collegeSlug'
    | '/dashboard/add-property'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/my-listings'
    | '/dashboard/settings'
    | '/listing/$slug'
    | '/dashboard/'
    | '/dashboard/edit-property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/flats-in-dehradun'
    | '/journal'
    | '/pg-hostels'
    | '/pg-in-dehradun'
    | '/pg-in-prem-nagar'
    | '/premium-homes'
    | '/press'
    | '/privacy'
    | '/properties-in-uttarakhand'
    | '/rooms-in-dehradun'
    | '/search-map'
    | '/security'
    | '/terms'
    | '/verified-owners'
    | '/wishlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/colleges/$collegeSlug'
    | '/dashboard/add-property'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/my-listings'
    | '/dashboard/settings'
    | '/listing/$slug'
    | '/dashboard'
    | '/dashboard/edit-property/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/flats-in-dehradun'
    | '/journal'
    | '/pg-hostels'
    | '/pg-in-dehradun'
    | '/pg-in-prem-nagar'
    | '/premium-homes'
    | '/press'
    | '/privacy'
    | '/properties-in-uttarakhand'
    | '/rooms-in-dehradun'
    | '/search-map'
    | '/security'
    | '/terms'
    | '/verified-owners'
    | '/wishlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/colleges/$collegeSlug'
    | '/dashboard/add-property'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/my-listings'
    | '/dashboard/settings'
    | '/listing/$slug'
    | '/dashboard/'
    | '/dashboard/edit-property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  FlatsInDehradunRoute: typeof FlatsInDehradunRoute
  JournalRoute: typeof JournalRoute
  PgHostelsRoute: typeof PgHostelsRoute
  PgInDehradunRoute: typeof PgInDehradunRoute
  PgInPremNagarRoute: typeof PgInPremNagarRoute
  PremiumHomesRoute: typeof PremiumHomesRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  PropertiesInUttarakhandRoute: typeof PropertiesInUttarakhandRoute
  RoomsInDehradunRoute: typeof RoomsInDehradunRoute
  SearchMapRoute: typeof SearchMapRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  VerifiedOwnersRoute: typeof VerifiedOwnersRoute
  WishlistRoute: typeof WishlistRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CollegesCollegeSlugRoute: typeof CollegesCollegeSlugRoute
  ListingSlugRoute: typeof ListingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-owners': {
      id: '/verified-owners'
      path: '/verified-owners'
      fullPath: '/verified-owners'
      preLoaderRoute: typeof VerifiedOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-map': {
      id: '/search-map'
      path: '/search-map'
      fullPath: '/search-map'
      preLoaderRoute: typeof SearchMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms-in-dehradun': {
      id: '/rooms-in-dehradun'
      path: '/rooms-in-dehradun'
      fullPath: '/rooms-in-dehradun'
      preLoaderRoute: typeof RoomsInDehradunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties-in-uttarakhand': {
      id: '/properties-in-uttarakhand'
      path: '/properties-in-uttarakhand'
      fullPath: '/properties-in-uttarakhand'
      preLoaderRoute: typeof PropertiesInUttarakhandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-homes': {
      id: '/premium-homes'
      path: '/premium-homes'
      fullPath: '/premium-homes'
      preLoaderRoute: typeof PremiumHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg-in-prem-nagar': {
      id: '/pg-in-prem-nagar'
      path: '/pg-in-prem-nagar'
      fullPath: '/pg-in-prem-nagar'
      preLoaderRoute: typeof PgInPremNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg-in-dehradun': {
      id: '/pg-in-dehradun'
      path: '/pg-in-dehradun'
      fullPath: '/pg-in-dehradun'
      preLoaderRoute: typeof PgInDehradunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg-hostels': {
      id: '/pg-hostels'
      path: '/pg-hostels'
      fullPath: '/pg-hostels'
      preLoaderRoute: typeof PgHostelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flats-in-dehradun': {
      id: '/flats-in-dehradun'
      path: '/flats-in-dehradun'
      fullPath: '/flats-in-dehradun'
      preLoaderRoute: typeof FlatsInDehradunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-listings': {
      id: '/dashboard/my-listings'
      path: '/my-listings'
      fullPath: '/dashboard/my-listings'
      preLoaderRoute: typeof DashboardMyListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/add-property': {
      id: '/dashboard/add-property'
      path: '/add-property'
      fullPath: '/dashboard/add-property'
      preLoaderRoute: typeof DashboardAddPropertyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/colleges/$collegeSlug': {
      id: '/colleges/$collegeSlug'
      path: '/colleges/$collegeSlug'
      fullPath: '/colleges/$collegeSlug'
      preLoaderRoute: typeof CollegesCollegeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/edit-property/$id': {
      id: '/dashboard/edit-property/$id'
      path: '/edit-property/$id'
      fullPath: '/dashboard/edit-property/$id'
      preLoaderRoute: typeof DashboardEditPropertyIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAddPropertyRoute: typeof DashboardAddPropertyRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMyListingsRoute: typeof DashboardMyListingsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEditPropertyIdRoute: typeof DashboardEditPropertyIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddPropertyRoute: DashboardAddPropertyRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMyListingsRoute: DashboardMyListingsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEditPropertyIdRoute: DashboardEditPropertyIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  FlatsInDehradunRoute: FlatsInDehradunRoute,
  JournalRoute: JournalRoute,
  PgHostelsRoute: PgHostelsRoute,
  PgInDehradunRoute: PgInDehradunRoute,
  PgInPremNagarRoute: PgInPremNagarRoute,
  PremiumHomesRoute: PremiumHomesRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  PropertiesInUttarakhandRoute: PropertiesInUttarakhandRoute,
  RoomsInDehradunRoute: RoomsInDehradunRoute,
  SearchMapRoute: SearchMapRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  VerifiedOwnersRoute: VerifiedOwnersRoute,
  WishlistRoute: WishlistRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CollegesCollegeSlugRoute: CollegesCollegeSlugRoute,
  ListingSlugRoute: ListingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
